# Generated by Django 3.2.7 on 2021-09-17 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0002_auto_20210917_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortner',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 17, 10, 20, 6, 77961)),
        ),
        migrations.AlterField(
            model_name='shortner',
            name='expirationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 17, 11, 20, 6, 77996)),
        ),
    ]
